### PR TITLE
Add index.html Page

### PR DESCRIPTION
**Pull request by sainingo**
### Hello Microverse Project PR description
The project is a simple web-page displaying an h1.
it has 3 commits.
Added the CSS file for styling the h1 above and .gitignore file

### CODE REVIEW

**Review by medaminedev66 — CHANGES_REQUESTED** [review]
Hi @sainingo   😃, wave:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- ✔️Git/GitHub flow best practices have been followed
- ✔️There are no linter errors

## Required Changes ♻️
- [ ] Kindly add a descriptive pull request description of what you have done in this pull request so that others can read what is being worked on.
- [ ] It will be nice if you could add a descriptive README file to your project. That file will give visitors a brief understanding of your project. Please use the [Microver template](https://github.com/microverseinc/readme-template) as an example.
- [ ] Please ignore the `node_modules/` folder using the .gitignore file. The node_modules/ folder is the folder where all packages required by your JavaScript project are downloaded and installed. This folder is commonly excluded from a remote repository because it has a large size and you shouldn’t add code that you didn’t write to the repository.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sainingo** [comment]
Hi @medaminedev66 
Thanks for the review 
I have worked on the changes as requested, kindly take a look

**Comment by sainingo** [comment]
### Hello Microverse Project PR description
The project is a simple web-page displaying an **h1**.
it has 3 commits.
Added the CSS file for styling the h1 above and .gitignore file

**Comment by medaminedev66** [comment]
Hi @sainingo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under your comment._

## Optional suggestions

- [OPTIONAL] The node_folder is still among the files in your repository. The easy approach to remove it from the GitHub repository is to delete locally and create a new commit and push it to GitHub.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by medaminedev66** [comment]
> ### Hello Microverse Project PR description
> The project is a simple web-page displaying an **h1**. it has 3 commits. Added the CSS file for styling the h1 above and .gitignore file

This is a comment. Not a pull request description. Let me help you to modify your pull request description:
- Click on the three-points icon I'm mentioning in the screenshot below:
image
- Then click on edit and paste your pull request description there:
image

**Review by medaminedev66 — CHANGES_REQUESTED** [review]
Hi @sainingo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under your comment._

## Optional suggestions

- [OPTIONAL] The node_folder is still among the files in your repository. The easy approach to remove it from the GitHub repository is to delete it locally, create a new commit and push it to GitHub.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by alexander16108 — APPROVED** [review]
Hi @sainingo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sainingo** [comment]
Thanks @alexander16108

**Pull request merged**
